In [1]:
from MS_sheets import * 
import MS

FileNotFoundError: [Errno 2] No such file or directory: 'discord/app/MS_sheets_credentials.json'

In [2]:
df = access_google_sheet(google_sheet_url=google_sheets_urls['hluwill'])

C:\Users\Micha\AppData\Local\Temp\ipykernel_30028\836761987.py:1: DeprecationWarning: [Deprecated][in version 6.0.0]: client_factory will be replaced by gspread.http_client types
  df = access_google_sheet(google_sheet_url=google_sheets_urls['hluwill'])

In [14]:
adjusted = MS.adjust_ba(df, 250)
minimum_ba = 1.3
supports, dps = MS.filter_players(adjusted, minimum_ba)
display(supports, dps)

,Timestamp,Character Name,Level,Class Type,BA,Party,level_diff,fd_multiplier,adjusted_BA
5,10/24/2023 11:31:13,f,245,Support,1.5,,-5,0.88,1.32

,Timestamp,Character Name,Level,Class Type,BA,Party,level_diff,fd_multiplier,adjusted_BA
8,10/24/2023 11:30:11,i,260,DPS,1.460165,,10,1.20,1.752198
3,10/24/2023 11:30:34,d,255,DPS,1.700000,,5,1.20,2.040000
2,10/24/2023 11:30:11,c,260,DPS,1.800000,,10,1.20,2.160000
9,10/24/2023 11:30:34,j,255,DPS,1.813683,,5,1.20,2.176419
7,10/24/2023 11:29:41,h,245,DPS,2.627418,,-5,0.88,2.312128
1,10/24/2023 11:29:41,b,245,DPS,2.700000,,-5,0.88,2.376000
4,10/24/2023 11:30:50,e,253,DPS,2.200000,,3,1.16,2.552000
10,10/24/2023 11:30:50,k,253,DPS,2.362146,,3,1.16,2.740089
0,10/24/2023 11:29:17,a,250,DPS,2.500000,,0,1.10,2.750000
6,10/24/2023 11:29:17,g,250,DPS,3.407284,,0,1.10,3.748012

In [15]:
result = MS.match_players(supports, dps, minimum_ba, minimum_ba*1.25)

No more elligible supports left
Total Party Damage 2.31212788664
Total Party Damage 4.68812788664
Total Party Damage 7.240127886640001
Total Party Damage 9.98021690212
Total Party Damage 2.75
Total Party Damage 6.498012424200001
[['f', 'i', 'd', 'c', 'j'], ['h', 'b', 'e', 'k']]

In [9]:
for party in result:
    print(adjusted.loc[adjusted["Character Name"].isin(party), "adjusted_BA"].sum())

12.816745011440002
11.79010143968

In [35]:
pd.concat([group.head(1) for _, group in df.sort_values(['Timestamp'], ascending=True).groupby('Character Name')])

,Timestamp,Character Name,Level,Class Type,BA,Party,level_diff,fd_multiplier,adjusted_BA
0,10/24/2023 11:29:17,a,250,DPS,2.500000,,0,1.10,2.750000
1,10/24/2023 11:29:41,b,245,DPS,2.700000,,-5,0.88,2.376000
2,10/24/2023 11:30:11,c,260,DPS,1.800000,,10,1.20,2.160000
3,10/24/2023 11:30:34,d,255,DPS,1.700000,,5,1.20,2.040000
4,10/24/2023 11:30:50,e,253,DPS,2.200000,,3,1.16,2.552000
6,10/24/2023 11:29:17,g,250,DPS,3.407284,,0,1.10,3.748012
7,10/24/2023 11:29:41,h,245,DPS,2.627418,,-5,0.88,2.312128
8,10/24/2023 11:30:11,i,260,DPS,1.460165,,10,1.20,1.752198
9,10/24/2023 11:30:34,j,255,DPS,1.813683,,5,1.20,2.176419
10,10/24/2023 11:30:50,k,253,DPS,2.362146,,3,1.16,2.740089
11,10/24/2023 11:31:13,l,245,Support,1.435424,,-5,0.88,1.263173

In [42]:
df.loc[df.groupby('Character Name')['Timestamp'].idxmin()]

,Timestamp,Character Name,Level,Class Type,BA,Party,level_diff,fd_multiplier,adjusted_BA
0,2023-10-24 11:29:17,a,250,DPS,2.500000,,0,1.10,2.750000
1,2023-10-24 11:29:41,b,245,DPS,2.700000,,-5,0.88,2.376000
2,2023-10-24 11:30:11,c,260,DPS,1.800000,,10,1.20,2.160000
3,2023-10-24 11:30:34,d,255,DPS,1.700000,,5,1.20,2.040000
4,2023-10-24 11:30:50,e,253,DPS,2.200000,,3,1.16,2.552000
6,2023-10-24 11:29:17,g,250,DPS,3.407284,,0,1.10,3.748012
7,2023-10-24 11:29:41,h,245,DPS,2.627418,,-5,0.88,2.312128
8,2023-10-24 11:30:11,i,260,DPS,1.460165,,10,1.20,1.752198
9,2023-10-24 11:30:34,j,255,DPS,1.813683,,5,1.20,2.176419
10,2023-10-24 11:30:50,k,253,DPS,2.362146,,3,1.16,2.740089
11,2023-10-24 11:31:13,l,245,Support,1.435424,,-5,0.88,1.263173

In [43]:
df

,Timestamp,Character Name,Level,Class Type,BA,Party,level_diff,fd_multiplier,adjusted_BA
0,2023-10-24 11:29:17,a,250,DPS,2.500000,,0,1.10,2.750000
1,2023-10-24 11:29:41,b,245,DPS,2.700000,,-5,0.88,2.376000
2,2023-10-24 11:30:11,c,260,DPS,1.800000,,10,1.20,2.160000
3,2023-10-24 11:30:34,d,255,DPS,1.700000,,5,1.20,2.040000
4,2023-10-24 11:30:50,e,253,DPS,2.200000,,3,1.16,2.552000
5,2023-10-24 11:31:13,a,245,Support,1.500000,,-5,0.88,1.320000
6,2023-10-24 11:29:17,g,250,DPS,3.407284,,0,1.10,3.748012
7,2023-10-24 11:29:41,h,245,DPS,2.627418,,-5,0.88,2.312128
8,2023-10-24 11:30:11,i,260,DPS,1.460165,,10,1.20,1.752198
9,2023-10-24 11:30:34,j,255,DPS,1.813683,,5,1.20,2.176419
10,2023-10-24 11:30:50,k,253,DPS,2.362146,,3,1.16,2.740089
11,2023-10-24 11:31:13,l,245,Support,1.435424,,-5,0.88,1.263173